-- =============================================================================
-- RBAC: Roles and grants with least-privilege access
-- Run as: ACCOUNTADMIN
-- 
-- Role hierarchy:
--   ACCOUNTADMIN
--     └── SYSADMIN
--           ├── INGESTION_ROLE      → writes to FIN_RAW_DB only
--           ├── DBT_TRANSFORM_ROLE  → reads FIN_RAW_DB, writes FIN_ANALYTICS_DB
--           └── ANALYST_ROLE        → read-only on FIN_ANALYTICS_DB.GOLD
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- ── Create databases ─────────────────────────────────────────
CREATE DATABASE IF NOT EXISTS FIN_RAW_DB
    COMMENT = 'Raw ingestion data: landing zone for SEC EDGAR, FRED, market data, FX rates'
;
CREATE DATABASE IF NOT EXISTS FIN_ANALYTICS_DB
    COMMENT = 'Transformed financial data: bronze, silver, gold medallion layers'
;

-- ── Create schemas in FIN_RAW_DB (one per source) ────────────
CREATE SCHEMA IF NOT EXISTS FIN_RAW_DB.SEC_EDGAR;
CREATE SCHEMA IF NOT EXISTS FIN_RAW_DB.FRED;
CREATE SCHEMA IF NOT EXISTS FIN_RAW_DB.MARKET_DATA;
CREATE SCHEMA IF NOT EXISTS FIN_RAW_DB.FX_RATES;

-- ── Create schemas in FIN_ANALYTICS_DB (medallion layers) ────
CREATE SCHEMA IF NOT EXISTS FIN_ANALYTICS_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS FIN_ANALYTICS_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS FIN_ANALYTICS_DB.GOLD;
CREATE SCHEMA IF NOT EXISTS FIN_ANALYTICS_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS FIN_ANALYTICS_DB.SNAPSHOTS;
CREATE SCHEMA IF NOT EXISTS FIN_ANALYTICS_DB.SEEDS;
CREATE SCHEMA IF NOT EXISTS FIN_ANALYTICS_DB.DEV;

-- ── Create roles ─────────────────────────────────────────────

CREATE ROLE IF NOT EXISTS INGESTION_ROLE
    COMMENT = 'Ingestion workloads: Snowpipe, Airflow. Write access to FIN_RAW_DB only.'
;

CREATE ROLE IF NOT EXISTS DBT_TRANSFORM_ROLE
    COMMENT = 'dbt transformation role: reads FIN_RAW_DB, writes FIN_ANALYTICS_DB.'
;

CREATE ROLE IF NOT EXISTS ANALYST_ROLE
    COMMENT = 'Analyst role: read-only access to FIN_ANALYTICS_DB.GOLD.'
;

-- ── Grant roles to SYSADMIN (role hierarchy) ─────────────────
GRANT ROLE INGESTION_ROLE TO ROLE SYSADMIN;
GRANT ROLE DBT_TRANSFORM_ROLE TO ROLE SYSADMIN;
GRANT ROLE ANALYST_ROLE TO ROLE SYSADMIN;

-- ── INGESTION_ROLE grants ────────────────────────────────────
-- Warehouse
GRANT USAGE ON WAREHOUSE INGESTION_WH TO ROLE INGESTION_ROLE;

-- FIN_RAW_DB: full write access
GRANT USAGE ON DATABASE FIN_RAW_DB TO ROLE INGESTION_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FIN_RAW_DB TO ROLE INGESTION_ROLE;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE FIN_RAW_DB TO ROLE INGESTION_ROLE;
GRANT CREATE STAGE ON ALL SCHEMAS IN DATABASE FIN_RAW_DB TO ROLE INGESTION_ROLE;
GRANT CREATE PIPE ON ALL SCHEMAS IN DATABASE FIN_RAW_DB TO ROLE INGESTION_ROLE;
GRANT INSERT, SELECT ON ALL TABLES IN DATABASE FIN_RAW_DB TO ROLE INGESTION_ROLE;

-- Future grants
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE FIN_RAW_DB TO ROLE INGESTION_ROLE;
GRANT SELECT, INSERT ON FUTURE TABLES IN DATABASE FIN_RAW_DB TO ROLE INGESTION_ROLE;

-- ── DBT_TRANSFORM_ROLE grants ────────────────────────────────
-- Warehouse
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE DBT_TRANSFORM_ROLE;

-- FIN_RAW_DB: read-only (dbt reads sources from here)
GRANT USAGE ON DATABASE FIN_RAW_DB TO ROLE DBT_TRANSFORM_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FIN_RAW_DB TO ROLE DBT_TRANSFORM_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE FIN_RAW_DB TO ROLE DBT_TRANSFORM_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE FIN_RAW_DB TO ROLE DBT_TRANSFORM_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE FIN_RAW_DB TO ROLE DBT_TRANSFORM_ROLE;

-- FIN_ANALYTICS_DB: full write access (dbt creates models here)
GRANT USAGE ON DATABASE FIN_ANALYTICS_DB TO ROLE DBT_TRANSFORM_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FIN_ANALYTICS_DB TO ROLE DBT_TRANSFORM_ROLE;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE FIN_ANALYTICS_DB TO ROLE DBT_TRANSFORM_ROLE;
GRANT CREATE VIEW ON ALL SCHEMAS IN DATABASE FIN_ANALYTICS_DB TO ROLE DBT_TRANSFORM_ROLE;
GRANT CREATE DYNAMIC TABLE ON ALL SCHEMAS IN DATABASE FIN_ANALYTICS_DB TO ROLE DBT_TRANSFORM_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE FIN_ANALYTICS_DB TO ROLE DBT_TRANSFORM_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE FIN_ANALYTICS_DB TO ROLE DBT_TRANSFORM_ROLE;

-- Future grants
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE FIN_ANALYTICS_DB TO ROLE DBT_TRANSFORM_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE FIN_ANALYTICS_DB TO ROLE DBT_TRANSFORM_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE FIN_ANALYTICS_DB TO ROLE DBT_TRANSFORM_ROLE;

-- ── ANALYST_ROLE grants ──────────────────────────────────────
-- Warehouse
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE ANALYST_ROLE;

-- FIN_ANALYTICS_DB: read-only on gold + silver
GRANT USAGE ON DATABASE FIN_ANALYTICS_DB TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA FIN_ANALYTICS_DB.GOLD TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA FIN_ANALYTICS_DB.SILVER TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FIN_ANALYTICS_DB.GOLD TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FIN_ANALYTICS_DB.GOLD TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FIN_ANALYTICS_DB.SILVER TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FIN_ANALYTICS_DB.SILVER TO ROLE ANALYST_ROLE;

-- Future grants
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIN_ANALYTICS_DB.GOLD TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIN_ANALYTICS_DB.GOLD TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIN_ANALYTICS_DB.SILVER TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIN_ANALYTICS_DB.SILVER TO ROLE ANALYST_ROLE;

-- ── Assign roles to users ────────────────────────────────────
-- Uncomment and replace with your actual Snowflake username
-- GRANT ROLE INGESTION_ROLE TO USER <your_username>;
-- GRANT ROLE DBT_TRANSFORM_ROLE TO USER <your_username>;
-- GRANT ROLE ANALYST_ROLE TO USER <your_username>;